# Generated by Django 5.2.7 on 2025-10-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='country_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('average_cost', models.PositiveIntegerField()),
                ('rating', models.IntegerField(verbose_name=range(1, 6))),
                ('image', models.ImageField(blank=True, null=True, upload_to='destination_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='destination_videos/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='base.country')),
            ],
        ),
    ]
